# its contents configure the TGIS server & caikit
jvm_options: []

runtime:
  library: caikit_nlp
  lazy_load_local_models: true
  batching:
    standalone-model:
      size: 0 # Set to batch size for batching

model_management:
  finders:
    default:
      type: LOCAL
  initializers:
    default:
      type: LOCAL
      config:
        backend_priority:
          - type: TGIS
            config:
              local:
                load_timeout: 120
                grpc_port: null
                http_port: null
                health_poll_delay: 1.0